<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_npru</name>
   <tag></tag>
   <elementGuidId>ff2cc910-2088-4c26-9b4f-d550a17573e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='tsf']/div/div/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.SDkEP</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bf707559-95d4-4ace-bdb3-c163c966ff69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SDkEP</value>
      <webElementGuid>bf6d1bae-c974-4d12-a252-df4fda01d3a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>กด / เพื่อข้ามไปยังช่องค้นหาnpru            </value>
      <webElementGuid>9e3af7e0-a1bc-417f-8760-88652190d796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tsf&quot;)/div[1]/div[@class=&quot;A8SBwf&quot;]/div[@class=&quot;RNNXgb&quot;]/div[@class=&quot;SDkEP&quot;]</value>
      <webElementGuid>5be2fbb5-67d8-450a-878b-83624378da27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='tsf']/div/div/div[3]/div</value>
      <webElementGuid>d7be2ea2-1a0a-434c-b24e-3d7c29c5fe50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div</value>
      <webElementGuid>2dde7657-5855-4ab7-b443-7f48a5dc7fd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'กด / เพื่อข้ามไปยังช่องค้นหาnpru            ' or . = 'กด / เพื่อข้ามไปยังช่องค้นหาnpru            ')]</value>
      <webElementGuid>31ff0f1a-f99d-4ed0-8a10-0f3084cb76b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
